### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackage-py#1]
# Description

Combining aspects from:

* https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/models.py
* https://github.com/trickvi/datapackage
* https://github.com/okfn/datapackage-init-js

Into a single model implementation around a DataPackage. Clearly will depend on the following to provide functionality:

* https://github.com/okfn/jsontableschema-py
* https://github.com/okfn/datapackage-validate-py
* https://github.com/okfn/datapackage-registry-py

# Tasks

* [x] Accept an existing datapackage (as json or as dict?)
  * [x] Ensure it validates
* [x] Init an empty data package (choose profile, defaults to "base")
* [x]  get/set values for the datapackage
  * [x] Note that the Data Package spec allows setting any properties that are not specified explicitly
* [x] Obviously the properties of the data package are generated based on the profile (from data package registry)
* [x] <del>get datapackage out as son</del> #16 
* [x] get data package out as dict
* [x] <del>Add a resource to a data package `resources` array</del> #14
* [x] <del>Useful helper methods:</del> #15
  * [x] <del>infer a schema for a resource, if we don't have one (Tabular Data Package)</del>
  * [x] <del>check that the data in a resource validates against the schema</del>
* [x] Good test coverage

**Comment by vitorbaptista** [comment]
Talking about the remaining issues:

### Obviously the properties of the data package are generated based on the profile (from data package registry)

I'm not sure what's needed here. When you create a new `datapackage.DataPackage()`, it'll be empty (`{}`) with the base schema, which isn't valid because the base schema required at least a `name`. The user can check that by using `.validate()` and `.required_attributes`, though, so it seems OK.

### Get datapackage out as json

I haven't implemented this because it feels not to belong to a `DataPackage` class. The user can get the data package as a dict (using `.to_dict()`) and convert to JSON himself using `json`, `ijson`, or whatever she prefers. It should be trivial to add this method, though, and I'd be happy to do so.

### Add a resource to a data package resources array

Check https://github.com/okfn/datapackage-py/issues/14

### Useful helper methods

https://github.com/okfn/jsontableschema-py/issues/40

**Comment by pwalsh** [comment]
@vitorbaptista i think we need our own to son method as we'll need to serialise values to particular formats (dates, etc.)

**Comment by vitorbaptista** [comment]
@pwalsh good point. I've created a separate issue to track this at https://github.com/okfn/datapackage-py/issues/16. That leaves undefined just the first point in my last message. If it's done, we could close this and add the separate issues to the current milestone.
